namespace ClientMinus.Models.MinusStore
{
    /// <summary>
    /// Weekly download statistic Generated by every-day command
    /// </summary>
    public class MinusWeekStats
    {
        public int Rate { get; set; }

        public object minus { get; set; }
    }
}